controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    gpio_command_controller:
      type: gpio_controllers/GpioCommandController

gpio_command_controller:
  ros__parameters:
    gpios:
      - gpio1
    state_interfaces:
      gpio1:
        - dig_input.1
        - dig_input.2
        - dig_input.3
        - dig_input.4
        - dig_input.5
        - dig_input.6
        - dig_input.7
        - dig_input.8
        - dig_input.9
        - dig_input.10
        - dig_input.11
        - dig_input.12
        - dig_input.13
        - dig_input.14
        - dig_input.15
        - dig_input.16
    command_interfaces:
      gpio1:
        - dig_input.1
        - dig_input.2
        - dig_input.3
        - dig_input.4
        - dig_input.5
        - dig_input.6
        - dig_input.7
        - dig_input.8
        - dig_input.9
        - dig_input.10
        - dig_input.11
        - dig_input.12
        - dig_input.13
        - dig_input.14
        - dig_input.15
        - dig_input.16